### ISSUE TITLE
Paypal order response

### ISSUE THREAD

**Issue by aiken94** [dbrax/paypal-laravel#1]
$response['order_id'] should be replaced with $response['payment_id']

**Comment by dbrax** [comment]
@aiken94  will check and respond to this thank you for the suggestion  , will keep this issue open for now

**Comment by aiken94** [comment]
It is on the package documentation
![IMG_20220526_191519](https://user-images.githubusercontent.com/49257458/170550604-e0147a98-1029-4ea4-8429-152d35132a38.jpg)
